### ISSUE TITLE
new co-maintainer, official repo?

### ISSUE THREAD

**Issue by chrstphrchvz** [asb-capfan/Tk-IDElayout#1]
Hi @asb-capfan, I recently got in touch with the existing maintainer of Tk::IDElayout (John Cerney) and have been added as a co-maintainer for it on PAUSE.

I'm interested in creating/designating an "official" repository for the module. I'm glad you've already created this one; would it be alright to start from the one you have, or are there other steps desirable for starting an official one (for example, adding commits corresponding to historical releases)? Your repository might also have some files leftover from Makefile.PL/`make` present (i.e. running `make clean` removes tracked files).

Let me know also if you'd like me to incorporate your improvements into a release. I don't have any substantial changes yet, so there's no hurry.

**Comment by asb-capfan** [comment]
Hi @chrstphrchvz !
Yes, please feel free to use this repository. It was meant for exactly this purpose.

I don't want to mirror the exact version history of the CPAN module here, as it doesn't really matter. It should be a way to easy propose pull requests.

An invitation for this repo was sent to you. I would be happy if this repo could become the official one of the module.

**Comment by chrstphrchvz** [comment]
I have uploaded Tk::IDElayout 0.34, containing your improved error message and META info for this GitHub repository. In a moment this will show up on metaCPAN as the "official" repository:

![screen shot 2018-08-02 at 11 21 58 am](https://user-images.githubusercontent.com/7941193/43596989-609f6f10-9646-11e8-8d5f-9232d99e9361.png)
